## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'thorlabs_delaytag'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_thorlabs_delaytag' #to modify
description = 'Set of PyMoDAQ plugins for instruments from Thorlabs (Kinesis K10CR1 (stepper rotation actuator), Kinesis Flipper, Kinesis KSP100, DCx camera...)'

author = 'Sébastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ["pythonnet", "pywin32", "nicelib", "instrumental-lib", "pylablib", "pymodaq<4", "pymodaq-plugins-thorlabs==0.3.0"]

